// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzJvm64kolLwXYTHkZthx_bLORS72I9sE',
    appId: '1:210013143763:android:5fb2c1308da61e7f0c0a26',
    messagingSenderId: '210013143763',
    projectId: 'bats-explorer-de16a',
    databaseURL: 'https://bats-explorer-de16a-default-rtdb.firebaseio.com',
    storageBucket: 'bats-explorer-de16a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmsWvFS6nw0fLscx3E3gXhmK1uE6DKxhs',
    appId: '1:210013143763:ios:379afde057a04ba10c0a26',
    messagingSenderId: '210013143763',
    projectId: 'bats-explorer-de16a',
    databaseURL: 'https://bats-explorer-de16a-default-rtdb.firebaseio.com',
    storageBucket: 'bats-explorer-de16a.appspot.com',
    iosClientId: '210013143763-dc9753fuolkva75hq3dg43ke66q9bcvk.apps.googleusercontent.com',
    iosBundleId: 'eco.beewise.batsexplorer',
  );
}
